apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sagar-matrimony
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password" # Change this for production
  JWT_SECRET: "your-super-secret-key" # Change this for production
